### PR TITLE
Kill profiler if timeout is reached

### PR DESCRIPTION
**Pull request by nsavoire**
# What does this PR do?

A brief description of the change being made with this pull request.

# Motivation

What inspired you to submit this pull request?  In order to motivate your point, it may be valuable to explain why this change is useful or what problem is being solved.

# Additional Notes

This is the section to put technical guidance/constraints, call out potential regressions, cite sources, and in general offer some exposition on the _how_ of the PR.  This section doesn't need to be incredibly detailed, but it makes life easier for reviewers!

# How to test the change?

Describe here in detail how the change can be validated.  This is a great section to call out specific tests you've added or improved, or to acknowledge code sections which are particularly difficult to test.

### CODE REVIEW

**Review by sanchda — APPROVED** [review]
Nice--looks good to me!

My only comment is that the initial `kill()` (line 187) and the check (line 191) will occur very close to each other in most systems, which may force a third `kill()` to be issued.  I don't think this matters, since this guarantees that `stop(0)` will send the kill signal at least one time, which I feel is important.  I sense it is better for `stop(0)` to do nonblocking stop rather than not stop at all.

**Comment by nsavoire** [comment]
> Nice--looks good to me!
> 
> My only comment is that the initial `kill()` (line 187) and the check (line 191) will occur very close to each other in most systems, which may force a third `kill()` to be issued. I don't think this matters, since this guarantees that `stop(0)` will send the kill signal at least one time, which I feel is important. I sense it is better for `stop(0)` to do nonblocking stop rather than not stop at all.

I moved the sleep before the check, does that sound good to you ?

**Review by sanchda — APPROVED** [review]
LGTM

**Comment by sanchda** [comment]
> > Nice--looks good to me!
> > My only comment is that the initial `kill()` (line 187) and the check (line 191) will occur very close to each other in most systems, which may force a third `kill()` to be issued. I don't think this matters, since this guarantees that `stop(0)` will send the kill signal at least one time, which I feel is important. I sense it is better for `stop(0)` to do nonblocking stop rather than not stop at all.
> 
> I moved the sleep before the check, does that sound good to you ?

Yup--the other way looked good, but this way looks better.  I expect that in the typical case, only one `kill()` needs to be sent.  It doesn't _really_ matter, but it could prevent an unnecessary 10ms wait when the user's application is performing its own time-critical shutdown operation.

**Pull request merged**
