### PR TITLE
Create a static ddprof exe on alpine/musl

### PR DESCRIPTION
**Pull request by nsavoire**
# What does this PR do?

Build a "universal" ddprof on Alpine/Musl:
*Statically link ddprof exe with musl libc, creating a static exe that has no dependencies.
*Create a loader library that depends on nothing except a few libc functions. The loader does not explicitly depend on libc, it expects a libc to be loaded be target process. Loader ensures that some libdl/libm symbols are available and dlopen the actual libdd_profiling library.

# Motivation

This should make ddprof / libdd_profiling.so compatible with all Linux distributions.

### CODE REVIEW

**Comment by nsavoire** [comment]
Current dependencies on/for this PR:
* main
  * **PR #159** <a href="https://app.graphite.dev/github/pr/DataDog/ddprof/159" target="_blank">Graphite</a> 
    * **PR #160** <a href="https://app.graphite.dev/github/pr/DataDog/ddprof/160" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/DataDog/ddprof/160?utm_source=stack-comment).

**Review by sanchda — APPROVED** [review]
Looks good!

It's not really necessary to check, but I did anyway.

Ubuntu 22.04:
```
$ ldd ./ddprof
        linux-vdso.so.1 (0x00007ffe9794f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0df58c2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0df6323000)
```

musl (alpine)
```
bash-5.1# ldd ./ddprof
/lib/ld-musl-x86_64.so.1: ./ddprof: Not a valid dynamic program
```
~44 megs in debug, ~41 in release (11 if stripped, which is something the user can easily do if they wish to).  Not bad for a static build.

**Comment by r1viollet** [comment]
This PR is very very cool. It comes with some amount of black magic.
After R&D we can talk about what it takes to feel good about merging this.

**Review by r1viollet — DISMISSED** [review]
LGTM
Thanks for making everything optional in the build system.
The new hook system is really amazing !

**Review by r1viollet — DISMISSED** [review]
LGTM

**Review by r1viollet — APPROVED** [review]
LGTM

**Pull request merged**
